services:
  jenkins:
    build: ./jenkins-master
    container_name: jenkins-cig
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Pour que Jenkins puisse piloter Docker
    user: root # Nécessaire pour accéder au socket Docker sur Windows/Linux

volumes:
  jenkins-data: